project_name: marketxiv
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/BitsOfAByte/marketxiv/build.Version={{.Version}}'
      - -X 'github.com/BitsOfAByte/marketxiv/build.Commit={{.Commit}}'
      - -X 'github.com/BitsOfAByte/marketxiv/build.Date={{.Date}}'
      - -X 'github.com/BitsOfAByte/marketxiv/build.SUPABASE_KEY={{ if index .Env "SUPABASE_KEY"  }}{{ .Env.SUPABASE_KEY }}{{ else }}none{{ end }}'

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github-native
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

brews:
  - tap:
      owner: BitsOfAByte
      name: marketxiv

    commit_author:
      name: github-actions
      email: actions@github.com

    commit_msg_template: "chore: Brew formula update for version {{ .Tag }}"
    description: |
      FFXIV Market CLI Tool
    homepage: "https://github.com/BitsOfAByte/MarketXIV"
    license: "MIT"

nfpms:
  - vendor: BitsOfAByte
    id: nfpm
    homepage: https://github.com/BitsOfAByte/MarketXIV
    maintainer: BitsOfAByte
    description: |
      FFXIV Market CLI Tool
    license: "MIT"
    formats:
      - deb
      - rpm

    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

    contents:
      - dst: ~/.config/marketxiv
        type: dir
        file_info:
          mode: 0755

      - dst: ~/.config/marketxiv/config.json
        type: ghost

publishers:
  - name: "packages.bitsofabyte.dev"
    dir: "{{ dir .ArtifactPath }}"
    ids:
      - nfpm
    cmd: |
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/BitsOfAByte/

scoop:
  bucket:
    owner: BitsOfAByte
    name: marketxiv

  commit_author:
    name: github-actions
    email: actions@github.com

  commit_msg_template: "chore: Scoop update for version {{ .Tag }}"
  description: "Final Fantasy 14 market information straight to your command line"
  homepage: "https://github.com/BitsOfAByte/MarketXIV"
  license: MIT

release:
  github:
    owner: BitsOfAByte
    name: MarketXIV
  prerelease: auto
