project_name: marketxiv
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - "-s -w -X 'github.com/BitsOfAByte/marketxiv/cmd.Version={{.Version}}'"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - tap:
      owner: BitsOfAByte
      name: marketxiv

    commit_author:
      name: github-actions
      email: actions@github.com

    commit_msg_template: "chore: Brew formula update for version {{ .Tag }}"
    license: "MIT"

scoop:
  bucket:
    owner: BitsOfAByte
    name: marketxiv

  commit_author:
    name: github-actions
    email: actions@github.com

  commit_msg_template: "chore: Scoop update for version {{ .Tag }}"
  license: MIT

release:
  github:
    owner: BitsOfAByte
    name: MarketXIV
  prerelease: auto
