name: Labels
on:
  schedule:
    - cron: '0 8 * * 2'
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          source-repo: BitsOfAByte/.github
          delete-other-labels: true
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
