name: PR

on:
  pull_request:
    branches: [main]

jobs:
  # Label the pull request with its file changes
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  # Check to see if an invalid file has been modified, if it has then fail. 
  No-Invalid-Edits: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Validate Edited Files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'json'
          filters: |
            src:
              - 'marketxiv.json'
              - 'marketxiv.rb' 
          
      - name: Fail CI on Invalid Edit
        if: steps.changes.outputs.src == 'true'
        run: | 
          echo "::error::Contains invalid file edits"
          exit 1
        
  # Check to see if any new dependency in this pull request is vulnerable.
  Dependency-Review:
    runs-on: ubuntu-latest
    needs: ["No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v1
          
  # Post a deploy preview comment when the pull request is opened
  Opened:
    if: ${{ github.event.action == 'opened'}}
    needs: ["No-Invalid-Edits", "Dependency-Review"]
    runs-on: ubuntu-latest
    steps:
      - name: Greet First Time Contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Thank you for your contribution! As you are a first time contributor, please ensure you have read the CONTRIBUTING guide to help make your PR the best it can be!"

      - name: Comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "A preview build for **${{ github.ref_name }}** is being generated, please wait. (ID: ${{ github.run_id }})"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  # If all is good, create a preview build for the pull request
  Preview:
    runs-on: ubuntu-latest
    needs: ["Dependency-Review", "No-Invalid-Edits"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPABASE_KEY: "unset"

      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/marketxiv_*_*/*
            checksums.txt

      - name: Edit Comment (Success)
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Success! A preview build was generated and can be downloaded from [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}).
            Please check the source code changes before downloading a build.
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit Comment (Failure)
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Deploy failed! Something went wrong while generating a preview build for this pull request."
          comment_includes: "preview build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
